set serveroutput on;

CREATE OR REPLACE TRIGGER KORISNIK_IME_UPDATE BEFORE
    UPDATE OF KORISNICKO_IME ON KORISNIK FOR EACH ROW WHEN(NEW.KORISNICKO_IME <> OLD.KORISNICKO_IME)
BEGIN
    DBMS_OUTPUT.PUT_LINE('Korisnik je promjenio ime.');
END KORISNIK_IME_UPDATE;
/

CREATE OR REPLACE TRIGGER PLAYLIST_IME_UPDATE BEFORE
    UPDATE OF NAZIV_PLAYLISTA ON PLAYLIST FOR EACH ROW WHEN(NEW.NAZIV_PLAYLISTA <> OLD.NAZIV_PLAYLISTA)
BEGIN
    DBMS_OUTPUT.PUT_LINE('Playlist je promjenio ime.');
END PLAYLIST_IME_UPDATE;
/

CREATE OR REPLACE TRIGGER DATUM_CHECK BEFORE INSERT OR UPDATE OF DATUM_OBJAVE ON PJESMA
    FOR EACH ROW
    BEGIN
    IF :NEW.DATUM_OBJAVE > SYSDATE THEN
        raise_application_error(-20001,'DATUM CHECK ERROR');
    END IF;
END DATUM_CHECK;
/
