CREATE OR REPLACE PROCEDURE ADD_TO_PLAYLIST(
    n_PLAYLIST_ID IN PLAYLIST.PLAYLIST_ID%TYPE,
    n_PJESMA_ID IN PJESMA.PJESMA_ID%TYPE
)AS BEGIN
    INSERT INTO PLAYLIST_PJESMA (PLAYLIST_ID, PJESMA_ID) VALUES
    (
        n_PLAYLIST_ID,
        n_PJESMA_ID
    );
    COMMIT;
    EXCEPTION WHEN OTHERS THEN
    ROLLBACK;
    raise_application_error(-20001,'ADD_TO_PLAYLIST ERROR');
END;
/

call ADD_TO_PLAYLIST(1,13);

CREATE OR REPLACE PROCEDURE DELETE_FROM_PLAYLIST(
    n_PLAYLIST_ID IN PLAYLIST.PLAYLIST_ID%TYPE,
    n_PJESMA_ID IN PJESMA.PJESMA_ID%TYPE
)AS BEGIN
    DELETE FROM PLAYLIST_PJESMA
    WHERE PLAYLIST_PJESMA.PLAYLIST_ID = n_PLAYLIST_ID AND PLAYLIST_PJESMA.PJESMA_ID = n_PJESMA_ID;
    COMMIT;
    EXCEPTION WHEN OTHERS THEN
    ROLLBACK;
    raise_application_error(-20001,'DELETE_FROM_PLAYLIST ERROR');
END;
/

cALL DELETE_FROM_PLAYLIST(1,13);