
DROP TABLE GLAZBENIK_PJESMA CASCADE CONSTRAINTS;
DROP TABLE PLAYLIST_PJESMA CASCADE CONSTRAINTS;
DROP TABLE PJESMA CASCADE CONSTRAINTS;
DROP TABLE ALBUM CASCADE CONSTRAINTS;
DROP TABLE PLAYLIST CASCADE CONSTRAINTS;
DROP TABLE GLAZBENIK CASCADE CONSTRAINTS;
DROP TABLE KORISNIK CASCADE CONSTRAINTS;
DROP TABLE ZANR CASCADE CONSTRAINTS;

CREATE TABLE GLAZBENIK(
    GLAZBENIK_ID INTEGER PRIMARY KEY,
    IME_GLAZBENIKA VARCHAR2( 30 ) NOT NULL
);

CREATE TABLE ALBUM(
    ALBUM_ID INTEGER PRIMARY KEY,
    NAZIV_ALBUMA VARCHAR2(30) NOT NULL,
    GLAZBENIK_ID NOT NULL REFERENCES GLAZBENIK(GLAZBENIK_ID)
);

CREATE TABLE ZANR(
    ZANR_ID INTEGER PRIMARY KEY,
    NAZIV_ZANRA VARCHAR2(30) NOT NULL
);

CREATE TABLE PJESMA(
    PJESMA_ID INTEGER PRIMARY KEY,
    NAZIV_PJESME VARCHAR2(100) NOT NULL,
    DATUM_OBJAVE DATE NOT NULL,
    ZANR_ID INTEGER NOT NULL REFERENCES ZANR(ZANR_ID),
    ALBUM_ID INTEGER REFERENCES ALBUM(ALBUM_ID)
);

CREATE TABLE KORISNIK(
    KORISNIK_ID INTEGER PRIMARY KEY,
    KORISNICKO_IME VARCHAR(30) NOT NULL
);

CREATE TABLE PLAYLIST(
    PLAYLIST_ID INTEGER PRIMARY KEY,
    NAZIV_PLAYLISTA VARCHAR(30) NOT NULL,
    KORISNIK_ID INTEGER NOT NULL REFERENCES KORISNIK(KORISNIK_ID)
);

CREATE TABLE GLAZBENIK_PJESMA(
    GLAZBENIK_ID INTEGER REFERENCES GLAZBENIK(GLAZBENIK_ID),
    PJESMA_ID INTEGER REFERENCES PJESMA(PJESMA_ID),
    PRIMARY KEY(GLAZBENIK_ID, PJESMA_ID)
);

CREATE TABLE PLAYLIST_PJESMA(
    PLAYLIST_ID INTEGER REFERENCES PLAYLIST(PLAYLIST_ID),
    PJESMA_ID INTEGER REFERENCES PJESMA(PJESMA_ID),
    PRIMARY KEY(PLAYLIST_ID, PJESMA_ID)
);