--jesnostavi upiti
SELECT
    IME_GLAZBENIKA
FROM
    GLAZBENIK;

SELECT
    NAZIV_PJESME
FROM
    PJESMA
WHERE
    DATUM_OBJAVE > TO_DATE('01/01/2016', 'DD/MM/YYYY');

SELECT
    NAZIV_ZANRA
FROM
    ZANR
WHERE
    ZANR_ID <> 2;

SELECT
    KORISNICKO_IME
FROM
    KORISNIK;

SELECT
    *
FROM
    PLAYLIST;

--upiti nad više tablica
--Sve pjesme od Arianae Grande
SELECT
    *
FROM
    PJESMA
    JOIN GLAZBENIK_PJESMA
    ON PJESMA.PJESMA_ID= GLAZBENIK_PJESMA.PJESMA_ID JOIN GLAZBENIK
    ON GLAZBENIK_PJESMA.GLAZBENIK_ID = GLAZBENIK.GLAZBENIK_ID
WHERE
    GLAZBENIK.IME_GLAZBENIKA = 'Ariana Grande';

--Sve pjesme starije od 1.1.2016. i ime njihovihovih izvođača
SELECT
    GLAZBENIK.IME_GLAZBENIKA,
    PJESMA.NAZIV_PJESME
FROM
    PJESMA
    JOIN GLAZBENIK_PJESMA
    ON PJESMA.PJESMA_ID = GLAZBENIK_PJESMA.PJESMA_ID JOIN GLAZBENIK
    ON GLAZBENIK_PJESMA.GLAZBENIK_ID = GLAZBENIK.GLAZBENIK_ID
WHERE
    TO_DATE('01/01/2016', 'DD/MM/YYYY') > PJESMA.DATUM_OBJAVE;

-- pjesme koje su u playlistu
SELECT
    PJESMA.NAZIV_PJESME,
    PLAYLIST.NAZIV_PLAYLISTA
FROM
    PJESMA
    JOIN PLAYLIST_PJESMA
    ON PJESMA.PJESMA_ID = PLAYLIST_PJESMA.PJESMA_ID JOIN PLAYLIST
    ON PLAYLIST_PJESMA.PLAYLIST_ID = PLAYLIST.PLAYLIST_ID
ORDER BY
    PLAYLIST.NAZIV_PLAYLISTA;

-- korisnici koji imaju playlist i ime playlista
SELECT
    KORISNIK.KORISNICKO_IME,
    PLAYLIST.NAZIV_PLAYLISTA
FROM
    KORISNIK
    JOIN PLAYLIST
    ON KORISNIK.KORISNIK_ID = PLAYLIST.PLAYLIST_ID;

-- glazbenici sa albumima i nazivi albuma
SELECT
    GLAZBENIK.IME_GLAZBENIKA,
    ALBUM.NAZIV_ALBUMA
FROM
    GLAZBENIK
    JOIN ALBUM
    ON GLAZBENIK.GLAZBENIK_ID = ALBUM.ALBUM_ID;

--upiti koji koriste agregirajuće funkcije
--ime albuma i broj pjesama u albumu
SELECT
    ALBUM.NAZIV_ALBUMA,
    COUNT(PJESMA.PJESMA_ID)
FROM
    PJESMA
    JOIN ALBUM
    ON ALBUM.ALBUM_ID = PJESMA.ALBUM_ID
GROUP BY
    ALBUM.NAZIV_ALBUMA;

--glazbenici koji imaju više od 1 pjesme
SELECT
    GLAZBENIK.IME_GLAZBENIKA
FROM
    GLAZBENIK
    JOIN GLAZBENIK_PJESMA
    ON GLAZBENIK_PJESMA.GLAZBENIK_ID = GLAZBENIK.GLAZBENIK_ID
GROUP BY
    GLAZBENIK.IME_GLAZBENIKA
HAVING
    COUNT(GLAZBENIK_PJESMA.PJESMA_ID) > 1;

--prosjecan broj pjesama u playlistu
SELECT
    AVG(COUNT(PJESMA.PJESMA_ID))
FROM
    PLAYLIST_PJESMA
    JOIN PJESMA
    ON PJESMA.PJESMA_ID = PLAYLIST_PJESMA.PJESMA_ID JOIN PLAYLIST
    ON PLAYLIST.PLAYLIST_ID = PLAYLIST_PJESMA.PLAYLIST_ID
GROUP BY
    PLAYLIST.PLAYLIST_ID;

--najviše pjesama što ima jedan glazbenik
SELECT
    MAX(COUNT(GLAZBENIK_PJESMA.PJESMA_ID))
FROM
    GLAZBENIK
    JOIN GLAZBENIK_PJESMA
    ON GLAZBENIK.GLAZBENIK_ID = GLAZBENIK_PJESMA.GLAZBENIK_ID JOIN PJESMA
    ON PJESMA.PJESMA_ID = GLAZBENIK_PJESMA.PJESMA_ID
GROUP BY
    GLAZBENIK_PJESMA.GLAZBENIK_ID;

--najmanje pjesama što ima jedan glazbenik
SELECT
    MIN(COUNT(GLAZBENIK_PJESMA.PJESMA_ID))
FROM
    GLAZBENIK
    JOIN GLAZBENIK_PJESMA
    ON GLAZBENIK.GLAZBENIK_ID = GLAZBENIK_PJESMA.GLAZBENIK_ID JOIN PJESMA
    ON PJESMA.PJESMA_ID = GLAZBENIK_PJESMA.PJESMA_ID
GROUP BY
    GLAZBENIK_PJESMA.GLAZBENIK_ID;

--svi glazbenici i pjevaci

SELECT
    GLAZBENIK.GLAZBENIK_ID,
    GLAZBENIK.IME_GLAZBENIKA,
    'GLAZBENIK'              AS "OPIS"
FROM
    GLAZBENIK UNION
    SELECT
        KORISNIK.KORISNIK_ID,
        KORISNIK.KORISNICKO_IME,
        'KORISNIK'               AS "OPIS"
    FROM
        KORISNIK;

--sve pjesme koje nisu u playlistu
SELECT
    PJESMA.PJESMA_ID,
    PJESMA.NAZIV_PJESME
FROM
    PJESMA
WHERE
    PJESMA.PJESMA_ID NOT IN (
        SELECT
            PJESMA.PJESMA_ID
        FROM
            PJESMA
            JOIN PLAYLIST_PJESMA
            ON PJESMA.PJESMA_ID = PLAYLIST_PJESMA.PJESMA_ID JOIN PLAYLIST
            ON PLAYLIST_PJESMA.PLAYLIST_ID = PLAYLIST.PLAYLIST_ID
    );

--svi glazbenici koji imaju pjesmu koja nije u albumu
SELECT
    GLAZBENIK.GLAZBENIK_ID,
    GLAZBENIK.IME_GLAZBENIKA
FROM
    GLAZBENIK MINUS
    SELECT
        GLAZBENIK.GLAZBENIK_ID,
        GLAZBENIK.IME_GLAZBENIKA
    FROM
        GLAZBENIK
        JOIN GLAZBENIK_PJESMA
        ON GLAZBENIK.GLAZBENIK_ID = GLAZBENIK_PJESMA.GLAZBENIK_ID JOIN PJESMA
        ON GLAZBENIK_PJESMA.PJESMA_ID = PJESMA.PJESMA_ID
    WHERE
        PJESMA.ALBUM_ID IS NOT NULL;

--sve pjesme koje nisu u playlistu ni u albumu
SELECT
    PJESMA.PJESMA_ID,
    PJESMA.NAZIV_PJESME
FROM
    PJESMA
WHERE
    PJESMA.PJESMA_ID NOT IN (
        SELECT
            PJESMA.PJESMA_ID
        FROM
            PJESMA
            JOIN PLAYLIST_PJESMA
            ON PJESMA.PJESMA_ID = PLAYLIST_PJESMA.PJESMA_ID JOIN PLAYLIST
            ON PLAYLIST_PJESMA.PLAYLIST_ID = PLAYLIST.PLAYLIST_ID
    )
    AND PJESMA.ALBUM_ID IS NULL;

--sve pjesme osim 5 najstarih
SELECT
    PJESMA.NAZIV_PJESME,
    PJESMA.DATUM_OBJAVE
FROM
    PJESMA
WHERE
    PJESMA.PJESMA_ID NOT IN (
        SELECT
            PJESMA.PJESMA_ID
        FROM
            PJESMA
        ORDER BY
            PJESMA.DATUM_OBJAVE ASC FETCH FIRST 5 ROWS ONLY
    );